# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [ ]:
import itertools
import glob

lst = ['A', 'B', 'C']
combinations = list(itertools.combinations(lst, 2))

print(*combinations)

**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [ ]:
sequence = itertools.cycle(['Python', 'is', 'fun'])

for _ in range(10):
    element = next(sequence)
    print(element)

**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [2]:
import glob
files_in_current_directory = glob.glob("*.py")

for file in files_in_current_directory:
    print(file)
    

**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [3]:
#

from bs4 import BeautifulSoup

def extract_paragraph_text(html_content):
    #parse the html content
    soup = BeautifulSoup(html_content, 'html.parser')
    paragraph = soup.find('p')
    if paragraph:
        text = paragraph.get_text(strip=True)
        return text
    else:
        return None
#html text
html = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"

# Extracting text from the <p> tag
paragraph_text = extract_paragraph_text(html)
print(paragraph_text)

AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [4]:
import re

def substitute(text, word, replacement):
    return re.sub(r'\b'+re.escape(word)+ r'\b',replacement,text)


text = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"

# replace the text
replaced_text = substitute(text, "AI", "Artificial Intelligence")
print(replaced_text)

<html><body><div class='main'><h1>Welcome to Artificial Intelligence</h1><p>Artificial Intelligence is transforming the world</p></div></body></html>


**CP6**: Create a numpy array of 10 zeros.

In [6]:
import numpy as np

#array of 10 zeros
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**CP7** Create a numpy array of the integers from 10 to 49.

In [9]:
#a numpy array of the integers from 10 to 49.
array = np.arange(10, 50) #numpy.arrange function it not inclusive

print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [10]:
#create an array and reshape it to 3x3
array = np.arange(0, 9)
matrix = array.reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

In [15]:
"""first machine learning (ML) models uses a large amount od  data to learn and
improve predictability and performance automatically through experience and data, without being
programmed to do so by humans.
it requires the right set of data that can be applied
to a learning process. big data can help improve the accuracy of machine learning models.

Big data is any kind of data source that has at least one of four
shared characteristics, called the four Vs:
1.Extremely large Volumes of data
2.The ability to move that data at a high Velocity of speed
3.An ever-expanding Variety of data sources
4.Veracity so that data sources truly represent truth
The accuracy of a machine learning model can increase substantially if it’s trained on big data. 
"""

'first machine learning (ML) models uses a large amount od  data to learn and\nimprove predictability and performance automatically through experience and data, without being\nprogrammed to do so by humans.\nit requires the right set of data that can be applied\nto a learning process. big data can help improve the accuracy of machine learning models.\n'

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

In [20]:
"""
1.Adversarial machine learning (AML) attacks are a growing threat to AI models. 
These attacks involve providing AI models with malicious inputs that can deceive the models into making incorrect predictions. 
One type of AML attack is poisoning attacks, which involve injecting carefully designed samples into training data. 
This can cause the model to learn incorrect patterns, which can lead to misclassifications in the future.
in order to prevent it we can implement the following defense strategies:
A.Block shifting is a defense strategy that assigns random run times to different parts of an AI model's layers. 
This strategy aims to confuse adversaries and prevent them from identifying and exploiting weaknesses in the model's layers.
B.Pruning is a method that removes infected neurons from a model. 
These neurons are entry points for backdoor attacks, which are a type of poisoning attack.





"""

"1.Adversarial machine learning (AML) attacks are a growing threat to AI models. \nThese attacks involve providing AI models with malicious inputs that can deceive the models into making incorrect predictions. \nOne type of AML attack is poisoning attacks, which involve injecting carefully designed samples into training data. \nThis can cause the model to learn incorrect patterns, which can lead to misclassifications in the future.\nin order to prevent it we can implement the following defense strategies:\nA.Block shifting is a defense strategy that assigns random run times to different parts of an AI model's layers. \nThis strategy aims to confuse adversaries and prevent them from identifying and exploiting weaknesses in the model's layers.\nB.Pruning is a method that removes infected neurons from a model. \nThese neurons are entry points for backdoor attacks, which are a type of poisoning attack.\n\n\n\n\n\n"