# numpy


In [34]:
import numpy as np

#check the version
np.__version__


'1.24.3'

In [35]:
array = np.array([1,2,3,4,5])
print(array)
#check the shape
print(array.shape)

#check the dimensin
array.ndim

[1 2 3 4 5]
(5,)


1

In [36]:
#0 dimensional array
array1 = np.array(67)
array1,type(array1), array1.shape ,array1.ndim

(array(67), numpy.ndarray, (), 0)

In [37]:
#2 dimensional array
array2 = np.array([[1,2,3],[1,2,3]])
print(array2,type(array2),array2.shape,array2.ndim)

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'> (2, 3) 2


In [38]:
#3d vector
array3 = np.array([[[1,2,3],[2,4,6]],[[1,7,4],[6,7,8]]])
array3.shape,array3.ndim

((2, 2, 3), 3)

# Array indexing and slicing

In [39]:
#index one dimensional array
array[-1]


5

In [40]:
array2

array([[1, 2, 3],
       [1, 2, 3]])

In [41]:
#we can index a two dimensiona array in two ways
print(array2[0][2])
array2[0,2]

3


3

In [42]:
array3

array([[[1, 2, 3],
        [2, 4, 6]],

       [[1, 7, 4],
        [6, 7, 8]]])

In [43]:
array3[0]

array([[1, 2, 3],
       [2, 4, 6]])

In [44]:
#from all columns of the 1 index slice 1 and 2 columns.
array3[1,:,1:3]

array([[7, 4],
       [7, 8]])

# data types

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type (void)

In [45]:
arrayd = np.array([1,2,3,4,5])
arrayd.dtype

dtype('int32')

In [47]:
arrayd1 = np.array([1,2,3,4,5.0])
arrayd1.dtype

dtype('float64')

In [50]:
arrayd2 = np.array(["mango","Avocado"])
arrayd2

array(['mango', 'Avocado'], dtype='<U7')

In [ ]:
#on the above dtype='<U7' means U = unicode string and 7 is the maimum length of the strings.