# numpy


In [2]:
import numpy as np

#check the version
np.__version__


'1.24.3'

In [12]:
array = np.array([1,2,3,4,5])
print(array)
#check the shape
print(array.shape)

#check the dimensin
array.ndim

[1 2 3 4 5]
(5,)


1

In [16]:
#0 dimensional array
array1 = np.array(67)
array1,type(array1), array1.shape ,array1.ndim

(array(67), numpy.ndarray, (), 0)

In [21]:
#2 dimensional array
array2 = np.array([[1,2,3],[1,2,3]])
print(array2,type(array2),array2.shape,array2.ndim)

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'> (2, 3) 2


In [22]:
#3d vector
